In [9]:
import pandas as pd
data={'slno':[1,2,3,4],'name':['albin','ajay','binu','sam']}
print("Dictionary : \n",data)
df=pd.DataFrame(data)
print("DataFrame : \n",df)

Dictionary :
 {'slno': [1, 2, 3, 4], 'name': ['albin', 'ajay', 'binu', 'sam']}
DataFrame :
    slno   name
0     1  albin
1     2   ajay
2     3   binu
3     4    sam