In [1]:
import pandas as pd
data=[['java','2000','200'],['cpp','3000','300'],['c','4000','400']]
print("List : \n",data)
data=pd.DataFrame(data)
print("DataFrame : \n",data)
print("\nFirst two rows of the dataframe : \n",data.head(2))

List :
 [['java', '2000', '200'], ['cpp', '3000', '300'], ['c', '4000', '400']]
DataFrame :
       0     1    2
0  java  2000  200
1   cpp  3000  300
2     c  4000  400

First two rows of the dataframe :
       0     1    2
0  java  2000  200
1   cpp  3000  300